services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - gamint

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - gamint

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      STORE_CORS: https://gamint.ir,https://www.gamint.ir,http://localhost:8000
      ADMIN_CORS: https://admin.gamint.ir,http://localhost:9000
      AUTH_CORS: https://admin.gamint.ir,https://gamint.ir,https://www.gamint.ir,http://localhost:9000,http://localhost:8000
      BACKEND_URL: https://admin.gamint.ir
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - backend_uploads:/app/static
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:9000/health >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    networks:
      - gamint


  storefront:
    build:
      context: .
      dockerfile: apps/storefront/Dockerfile
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: http://backend:9000
      NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY: pk_4674f31183ed77aa2bd1f9cb3c9aa0c014b8f4c72788b4d9378f4075492ff227
      NEXT_PUBLIC_DEFAULT_REGION: ir
      NEXT_PUBLIC_BASE_URL: http://127.0.0.1:8000
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - gamint

volumes:
  postgres_data:
  redis_data:
  backend_uploads:

networks:
  gamint:
